services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - letsencrypt:/etc/letsencrypt:ro
      - certbot-www:/var/www/certbot
    depends_on:
      - backend
      - frontend
    restart: always

  certbot:
    image: certbot/certbot
    volumes:
      - letsencrypt:/etc/letsencrypt
      - certbot-www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    restart: always

  backend:
    build:
      context: ./backend
    expose:
      - "8000"
    volumes:
      - backend-storage:/app/storage
      - ./backend/src:/app/src  # Mount source code for development
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_MODEL=${OPENAI_MODEL:-gpt-4o-mini}
      - ADMIN_REGISTRATION_SECRET=${ADMIN_REGISTRATION_SECRET:-admin123}
      - USER_REGISTRATION_SECRET=${USER_REGISTRATION_SECRET:-user123}
      - MAX_DOCUMENT_SIZE=${MAX_DOCUMENT_SIZE:-4000}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_CACHE_TTL=3600
      - ALLOWED_ORIGINS=http://localhost,https://localhost,https://${DOMAIN_NAME:-osamusic.org},https://${DOMAIN_ALIASES:-www.osamusic.org}
      - ALLOWED_HOSTS=localhost,${DOMAIN_NAME:-osamusic.org},${DOMAIN_ALIASES:-www.osamusic.org}
      - FIREBASE_API_KEY=${FIREBASE_API_KEY}
      - FIREBASE_SERVICE_ACCOUNT_JSON=${FIREBASE_SERVICE_ACCOUNT_JSON}
      - DATABASE_URL=${DATABASE_URL:-mssql+pyodbc://${DB_USER}:${DB_PASSWORD}@cloud-sql-proxy:1433/${DB_NAME}?driver=ODBC+Driver+18+for+SQL+Server&TrustServerCertificate=yes}
      - CLOUD_SQL_CONNECTION_NAME=${CLOUD_SQL_CONNECTION_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - redis
      - cloud-sql-proxy
    restart: always

  frontend:
    build:
      context: ./frontend
      args:
        - VITE_API_URL=https://localhost/api
        - NODE_ENV=development
        - VITE_ALLOWED_HOSTS=localhost,${DOMAIN_NAME:-osamusic.org},${DOMAIN_ALIASES:-www.osamusic.org}
        - VITE_GOOGLE_CLIENT_ID=${VITE_GOOGLE_CLIENT_ID}
    expose:
      - "5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_ALLOWED_HOSTS=localhost,${DOMAIN_NAME:-osamusic.org},${DOMAIN_ALIASES:-www.osamusic.org}
      - VITE_GOOGLE_CLIENT_ID=${VITE_GOOGLE_CLIENT_ID}
    depends_on:
      - backend
    restart: always
      
  redis:
    image: redis:alpine
    expose:
      - "6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    restart: always

  cloud-sql-proxy:
    image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:latest
    command:
      - "--port=1433"
      - "--address=0.0.0.0"
      - "${CLOUD_SQL_CONNECTION_NAME}"
    volumes:
      - ${SERVICE_ACCOUNT_FILE:-./service-account.json}:/config/service-account.json:ro
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/config/service-account.json
    expose:
      - "1433"
    restart: always

volumes:
  redis-data:
  backend-storage:
  letsencrypt:
  certbot-www:
